language: objective-c
osx_image: xcode6.4
before_install:
- gem install xcpretty
script:
- set -o pipefail

# Disabled until Travis supports Xcode 7 :-(
#- xcodebuild -project Toucan.xcodeproj -scheme "ToucanTests" test -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO | xcpretty -c
